/**
 * NHANES 2017-2018 percentile lookup for biomarkers and phenotypic age.
 *
 * Reference data: data/nhanes_reference.json
 * Generated by: scripts/process_nhanes.py
 * Source: CDC/NCHS, NHANES 2017-2018 (cycle J)
 */

import nhanesRef from '../../../data/nhanes_reference.json'
import type { BiomarkerKey } from '@/types/biomarkers'

// ─── Reference Data Types ─────────────────────────────────────────────────────

interface StratumStats {
  n: number
  mean: number
  sd: number
  p5:  number
  p10: number
  p25: number
  p50: number
  p75: number
  p90: number
  p95: number
}

interface Stratum {
  n: number
  phenoage?: StratumStats
  albumin?: StratumStats
  creatinine?: StratumStats
  glucose?: StratumStats
  crp?: StratumStats
  lymphocytePct?: StratumStats
  mcv?: StratumStats
  rdw?: StratumStats
  alp?: StratumStats
  wbc?: StratumStats
}

type NhanesRef = {
  version: string
  strata: Record<string, Stratum>
}

const ref = nhanesRef as NhanesRef

// ─── Age Bin Resolution ───────────────────────────────────────────────────────

/**
 * Map a continuous age to its NHANES stratum age-range string.
 * Returns null if the age is outside the NHANES 2017-2018 collection range (18–89).
 * We do NOT extrapolate outside the reference population.
 */
function ageBinFor(age: number): string | null {
  const bins: [number, number][] = [
    [18, 30], [30, 40], [40, 50],
    [50, 60], [60, 70], [70, 80], [80, 90],
  ]
  for (const [lo, hi] of bins) {
    if (age >= lo && age < hi) return `${lo}_${hi}`
  }
  return null
}

function getStratum(age: number, sex: 'male' | 'female'): Stratum | null {
  const bin = ageBinFor(age)
  if (!bin) return null
  return ref.strata[`${sex}_${bin}`] ?? null
}

// ─── Interpolation ────────────────────────────────────────────────────────────

/** Known (value, percentile) anchor pairs within a distribution. */
const ANCHORS: [keyof StratumStats, number][] = [
  ['p5',  5],
  ['p10', 10],
  ['p25', 25],
  ['p50', 50],
  ['p75', 75],
  ['p90', 90],
  ['p95', 95],
]

/**
 * Interpolate (or extrapolate) the percentile rank of `value` within `stats`.
 * Returns a percentile in the range 1–99.
 *
 * Algorithm:
 *   - Within [p5, p95]: linear interpolation between surrounding anchor points.
 *   - Outside [p5, p95]: linear extrapolation using the slope of the nearest
 *     pair of anchors, clamped to [1, 99].
 */
function interpolatePercentile(value: number, stats: StratumStats): number {
  const points = ANCHORS.map(([key, pct]) => ({ val: stats[key], pct }))

  // Below the lowest known anchor (p5)
  if (value <= points[0].val) {
    const slope = slopeBetween(points[0], points[1])
    return Math.max(1, points[0].pct + slope * (value - points[0].val))
  }

  // Above the highest known anchor (p95)
  const last = points[points.length - 1]
  const prev = points[points.length - 2]
  if (value >= last.val) {
    const slope = slopeBetween(prev, last)
    return Math.min(99, last.pct + slope * (value - last.val))
  }

  // Between two anchor points — linear interpolation
  for (let i = 0; i < points.length - 1; i++) {
    const lo = points[i]!
    const hi = points[i + 1]!
    if (value >= lo.val && value <= hi.val) {
      if (hi.val === lo.val) return lo.pct
      const t = (value - lo.val) / (hi.val - lo.val)
      return lo.pct + t * (hi.pct - lo.pct)
    }
  }

  return 50 // fallback (should not be reached)
}

function slopeBetween(
  a: { val: number; pct: number },
  b: { val: number; pct: number },
): number {
  if (b.val === a.val) return 0
  return (b.pct - a.pct) / (b.val - a.val)
}

// ─── Public API ───────────────────────────────────────────────────────────────

/**
 * Returns the NHANES percentile rank (1–99) for a biomarker value,
 * stratified by the user's chronological age and sex.
 *
 * Returns null if the stratum or biomarker has no reference data.
 */
export function getBiomarkerPercentile(
  key: BiomarkerKey,
  value: number,
  age: number,
  sex: 'male' | 'female',
): number | null {
  const stratum = getStratum(age, sex)
  if (!stratum) return null

  const stats = stratum[key]
  if (!stats) return null

  return Math.round(interpolatePercentile(value, stats) * 10) / 10
}

/**
 * Returns the NHANES percentile rank (1–99) for a computed PhenoAge value,
 * compared to the user's age/sex-matched cohort.
 *
 * A lower percentile means biologically younger relative to peers.
 * Returns null if the stratum has no phenoage reference data.
 */
export function getPhenoAgePercentile(
  biologicalAge: number,
  chronologicalAge: number,
  sex: 'male' | 'female',
): number | null {
  const stratum = getStratum(chronologicalAge, sex)
  if (!stratum?.phenoage) return null

  return Math.round(interpolatePercentile(biologicalAge, stratum.phenoage) * 10) / 10
}

/**
 * Returns the full distribution stats for a biomarker in the given stratum.
 * Useful for rendering reference range indicators in charts.
 */
export function getBiomarkerStats(
  key: BiomarkerKey,
  age: number,
  sex: 'male' | 'female',
): StratumStats | null {
  const stratum = getStratum(age, sex)
  if (!stratum) return null
  return stratum[key] ?? null
}

/**
 * Returns the PhenoAge distribution stats for the given age/sex stratum.
 */
export function getPhenoAgeStats(
  age: number,
  sex: 'male' | 'female',
): StratumStats | null {
  const stratum = getStratum(age, sex)
  return stratum?.phenoage ?? null
}

/**
 * All available stratum keys in the reference dataset.
 * Useful for validating coverage and debugging.
 */
export const AVAILABLE_STRATA = Object.keys(ref.strata)

/** Metadata about the reference dataset. */
export const REFERENCE_META = {
  version:   ref.version,
  citation:  (ref as { citation?: string }).citation ?? '',
  algorithm: (ref as { algorithm?: string }).algorithm ?? '',
} as const
